# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 20:34
from __future__ import unicode_literals

import app.market.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('description', tinymce.models.HTMLField(blank=True, verbose_name='Описание оборудования')),
                ('available', models.BooleanField(default=True, verbose_name='Доcтупен сейчас')),
                ('cover', models.ImageField(blank=True, upload_to=app.market.models.upload_to, verbose_name='Выбрать фотографию обложки')),
                ('hover_cover', models.ImageField(blank=True, upload_to=app.market.models.upload_to, verbose_name='Выбрать фотографию ховера обложки')),
                ('sort_index', models.PositiveIntegerField(default=0, verbose_name='Индекс сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('title', models.CharField(max_length=256, verbose_name='Короткое описание')),
                ('audience', models.TextField(verbose_name='Аудитория')),
                ('accessibility', models.TextField(verbose_name='Доступность')),
                ('easy_to_use', models.TextField(verbose_name='Простота использования')),
                ('author', models.CharField(max_length=256, verbose_name='Автор')),
                ('count_pages', models.PositiveIntegerField(verbose_name='Количество страниц')),
                ('date_publication', models.PositiveIntegerField(help_text='Use the following format: <YYYY>', null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2017)], verbose_name='Дата публикации')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BooksImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=app.market.models.upload_to, verbose_name='Изображение')),
                ('sorting', models.PositiveIntegerField(blank=True, default=0, verbose_name='Сортировка')),
                ('goods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='market.Books', verbose_name='Фото для товара')),
            ],
            options={
                'verbose_name_plural': 'Фотографии товара',
                'ordering': ['sorting'],
                'verbose_name': 'Фотография товара',
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название каталога')),
                ('slug', models.SlugField(null=True, verbose_name='URL')),
            ],
            options={
                'verbose_name_plural': 'Каталоги товаров',
                'verbose_name': 'Каталог товара',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название категории')),
                ('sort_index', models.PositiveIntegerField(default=0, verbose_name='Индекс сортировки')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogs', to='market.Catalog', verbose_name='Каталог')),
            ],
            options={
                'verbose_name_plural': 'Категории товаров',
                'ordering': ['sort_index'],
                'verbose_name': 'Категория товара',
            },
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('description', tinymce.models.HTMLField(blank=True, verbose_name='Описание оборудования')),
                ('available', models.BooleanField(default=True, verbose_name='Доcтупен сейчас')),
                ('cover', models.ImageField(blank=True, upload_to=app.market.models.upload_to, verbose_name='Выбрать фотографию обложки')),
                ('hover_cover', models.ImageField(blank=True, upload_to=app.market.models.upload_to, verbose_name='Выбрать фотографию ховера обложки')),
                ('sort_index', models.PositiveIntegerField(default=0, verbose_name='Индекс сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes_categories', to='market.Category', verbose_name='Категория товаров')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClothesImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=app.market.models.upload_to, verbose_name='Изображение')),
                ('sorting', models.PositiveIntegerField(blank=True, default=0, verbose_name='Сортировка')),
                ('goods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='market.Clothes', verbose_name='Фото для товара')),
            ],
            options={
                'verbose_name_plural': 'Фотографии товара',
                'ordering': ['sorting'],
                'verbose_name': 'Фотография товара',
            },
        ),
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_categories', to='market.Category', verbose_name='Категория товаров'),
        ),
    ]
