# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='height',
            field=models.PositiveIntegerField(default=0, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='books',
            name='length',
            field=models.PositiveIntegerField(default=0, verbose_name='Длина'),
        ),
        migrations.AddField(
            model_name='books',
            name='weight',
            field=models.FloatField(default=0.0, verbose_name='Вес'),
        ),
        migrations.AddField(
            model_name='books',
            name='width',
            field=models.PositiveIntegerField(default=0, verbose_name='Ширина'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='height',
            field=models.PositiveIntegerField(default=0, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='length',
            field=models.PositiveIntegerField(default=0, verbose_name='Длина'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='weight',
            field=models.FloatField(default=0.0, verbose_name='Вес'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='width',
            field=models.PositiveIntegerField(default=0, verbose_name='Ширина'),
        ),
    ]
