# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 14:58
from __future__ import unicode_literals

import app.market.models
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20171106_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dvd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('description', tinymce.models.HTMLField(blank=True, verbose_name='Описание оборудования')),
                ('available', models.BooleanField(default=True, verbose_name='Доcтупен сейчас')),
                ('cover', models.ImageField(blank=True, upload_to=app.market.models.upload_to, verbose_name='Выбрать фотографию обложки')),
                ('hover_cover', models.ImageField(blank=True, upload_to=app.market.models.upload_to, verbose_name='Выбрать фотографию ховера обложки')),
                ('sort_index', models.PositiveIntegerField(default=0, verbose_name='Индекс сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('width', models.PositiveIntegerField(default=0, verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='Высота')),
                ('length', models.PositiveIntegerField(default=0, verbose_name='Длина')),
                ('weight', models.FloatField(default=0.0, verbose_name='Вес')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dvd_categories', to='market.Category', verbose_name='Категория товаров')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Souvenirs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('description', tinymce.models.HTMLField(blank=True, verbose_name='Описание оборудования')),
                ('available', models.BooleanField(default=True, verbose_name='Доcтупен сейчас')),
                ('cover', models.ImageField(blank=True, upload_to=app.market.models.upload_to, verbose_name='Выбрать фотографию обложки')),
                ('hover_cover', models.ImageField(blank=True, upload_to=app.market.models.upload_to, verbose_name='Выбрать фотографию ховера обложки')),
                ('sort_index', models.PositiveIntegerField(default=0, verbose_name='Индекс сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('width', models.PositiveIntegerField(default=0, verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='Высота')),
                ('length', models.PositiveIntegerField(default=0, verbose_name='Длина')),
                ('weight', models.FloatField(default=0.0, verbose_name='Вес')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='souvenirs_categories', to='market.Category', verbose_name='Категория товаров')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
