# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 22:14
from __future__ import unicode_literals

import app.market.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_dvd_souvenirs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('description', tinymce.models.HTMLField(blank=True, verbose_name='Описание')),
                ('available', models.BooleanField(default=True, verbose_name='Доcтупен сейчас')),
                ('cover', models.ImageField(blank=True, upload_to=app.market.models.upload_to, verbose_name='Выбрать фотографию обложки')),
                ('hover_cover', models.ImageField(blank=True, upload_to=app.market.models.upload_to, verbose_name='Выбрать фотографию ховера обложки')),
                ('sort_index', models.PositiveIntegerField(default=0, verbose_name='Индекс сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('width', models.PositiveIntegerField(default=0, verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='Высота')),
                ('length', models.PositiveIntegerField(default=0, verbose_name='Длина')),
                ('weight', models.FloatField(default=0.0, verbose_name='Вес')),
                ('title', models.CharField(max_length=256, null=True, verbose_name='Короткое описание')),
                ('audience', models.TextField(null=True, verbose_name='Аудитория')),
                ('accessibility', models.TextField(null=True, verbose_name='Доступность')),
                ('easy_to_use', models.TextField(null=True, verbose_name='Простота использования')),
                ('author', models.CharField(max_length=256, null=True, verbose_name='Автор')),
                ('count_pages', models.PositiveIntegerField(null=True, verbose_name='Количество страниц')),
                ('format', models.CharField(max_length=512, null=True, verbose_name='Формат')),
                ('date_publication', models.PositiveIntegerField(help_text='Use the following format: <YYYY>', null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2017)], verbose_name='Дата публикации')),
                ('size', models.CharField(choices=[('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL')], max_length=12, null=True, verbose_name='Размер для одежды')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books_categories', to='market.Category', verbose_name='Категория товаров')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Тип товара')),
            ],
            options={
                'verbose_name': 'Тип товара',
                'verbose_name_plural': 'Типы товаров',
            },
        ),
        migrations.RenameModel(
            old_name='BooksImage',
            new_name='GoodsImage',
        ),
        migrations.RemoveField(
            model_name='books',
            name='category',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='category',
        ),
        migrations.RemoveField(
            model_name='clothesimage',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='dvd',
            name='category',
        ),
        migrations.RemoveField(
            model_name='souvenirs',
            name='category',
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='market.Goods', verbose_name='Фото для товара'),
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='Clothes',
        ),
        migrations.DeleteModel(
            name='ClothesImage',
        ),
        migrations.DeleteModel(
            name='Dvd',
        ),
        migrations.DeleteModel(
            name='Souvenirs',
        ),
        migrations.AddField(
            model_name='goods',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_types', to='market.Type', verbose_name='Тип'),
        ),
    ]
