# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 15:01
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20171116_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Описание категории'),
        ),
        migrations.AddField(
            model_name='goods',
            name='is_main',
            field=models.BooleanField(default=True, verbose_name='Выводить на главной'),
        ),
    ]
