# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 15:03
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20171119_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Описание'),
        ),
    ]
