# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_auto_20171119_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Выводить на главной'),
        ),
    ]
