# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 21:56
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_auto_20171121_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='articul',
            field=models.CharField(max_length=256, null=True, verbose_name='Артикул товара'),
        ),
        migrations.AddField(
            model_name='goods',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='meta description'),
        ),
        migrations.AddField(
            model_name='goods',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='meta keywords'),
        ),
        migrations.AddField(
            model_name='goods',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='meta title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Описание категории'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Описание'),
        ),
    ]
