# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_auto_20171204_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
    ]
