# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-18 20:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_auto_20171204_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='date_publication',
            field=models.PositiveIntegerField(blank=True, help_text='Введите год публикации книги <YYYY>', null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2018)], verbose_name='Дата публикации'),
        ),
    ]
