# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20171201_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='show_bottom',
            field=models.BooleanField(default=False, verbose_name='Пoказывать в футере'),
        ),
        migrations.AddField(
            model_name='page',
            name='show_top',
            field=models.BooleanField(default=False, verbose_name='Пoказывать в хэдере'),
        ),
    ]
