# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 16:27
from __future__ import unicode_literals

import app.market.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeftBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('title', models.CharField(blank=True, max_length=256, verbose_name='Заголовок')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Описание')),
                ('cover', models.ImageField(blank=True, upload_to=app.market.models.upload_to, verbose_name='Обложка')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка слайда')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
            },
        ),
        migrations.CreateModel(
            name='LeftSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, upload_to=app.market.models.upload_to, verbose_name='Обложка слайда')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка слайда')),
                ('sort_index', models.PositiveIntegerField(default=0, verbose_name='Индекс сортировки')),
            ],
            options={
                'verbose_name': 'Слайд',
                'ordering': ['sort_index'],
                'verbose_name_plural': 'Слайды',
            },
        ),
        migrations.CreateModel(
            name='LeftSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Левый слайдер')),
            ],
            options={
                'verbose_name': 'Левый слайдер',
                'verbose_name_plural': 'Левые слайдеры',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Слайдер')),
            ],
            options={
                'verbose_name': 'Верхний слайдер',
                'verbose_name_plural': 'Верхние слайдеры',
            },
        ),
        migrations.CreateModel(
            name='TopBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, upload_to=app.market.models.upload_to, verbose_name='Обложка слайда')),
            ],
        ),
        migrations.CreateModel(
            name='TopSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, upload_to=app.market.models.upload_to, verbose_name='Обложка слайда')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка слайда')),
                ('sort_index', models.PositiveIntegerField(default=0, verbose_name='Индекс сортировки')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_sliders', to='mainpage.Slider', verbose_name='Слайдер')),
            ],
            options={
                'verbose_name': 'Слайд',
                'ordering': ['sort_index'],
                'verbose_name_plural': 'Слайды',
            },
        ),
        migrations.AddField(
            model_name='leftslide',
            name='slider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_sliders', to='mainpage.LeftSlider', verbose_name='Слайдер'),
        ),
    ]
