# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20171119_2014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topbanner',
            options={'verbose_name': 'Верхний баннер', 'verbose_name_plural': 'Верхний баннеры'},
        ),
    ]
