# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20171201_0056'),
        ('mainpage', '0003_auto_20171120_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='leftblog',
            name='pages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Blog_page', to='pages.Page', verbose_name='Страница'),
        ),
    ]
