# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 11:02
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_auto_20171203_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leftabout',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
