# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20171125_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='save_info',
        ),
        migrations.AddField(
            model_name='order',
            name='home',
            field=models.CharField(max_length=256, null=True, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_delivery',
            field=models.CharField(choices=[('shiptor', 'shiptor'), ('boxberry', 'boxberry'), ('b2c', 'b2c'), ('dpd', 'dpd'), ('iml', 'iml'), ('russian-post', 'russian-post'), ('pickpoint', 'pickpoint'), ('cdek', 'cdek'), ('shiptor-one-day', 'shiptor-one-day'), ('spsr', 'spsr'), ('shiptor-oversize', 'shiptor-oversize')], max_length=16, null=True, verbose_name='Способ доставки'),
        ),
    ]
