# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20171127_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_delivery',
            field=models.CharField(choices=[('shiptor', 'shiptor'), ('boxberry', 'boxberry'), ('b2c', 'b2c'), ('dpd', 'dpd'), ('iml', 'iml'), ('russian-post', 'Почта России'), ('pickpoint', 'pickpoint'), ('cdek', 'cdek'), ('shiptor-one-day', 'shiptor-one-day'), ('spsr', 'spsr'), ('shiptor-oversize', 'shiptor-oversize')], max_length=16, null=True, verbose_name='Способ доставки'),
        ),
    ]
