# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20171201_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('waiting', 'Ожидание'), ('processing', 'В обработке'), ('paid', 'Оплачено онлайн'), ('confirmed', 'Подтвержден'), ('cancel', 'Отменен')], max_length=10, verbose_name='Статус заказа'),
        ),
    ]
