# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20171204_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Cумма заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_delivery',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Cтоимость доставки'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
        ),
    ]
