# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20171204_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='administrative_area',
            field=models.CharField(max_length=256, null=True, verbose_name='Область'),
        ),
        migrations.AddField(
            model_name='order',
            name='apartment',
            field=models.CharField(max_length=256, null=True, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_point',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='ID пункта самовывоза'),
        ),
        migrations.AddField(
            model_name='order',
            name='kladr_id',
            field=models.PositiveIntegerField(default=0, verbose_name='kladr_id'),
        ),
        migrations.AddField(
            model_name='order',
            name='settlement',
            field=models.CharField(max_length=256, null=True, verbose_name='Населенный пункт'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_id',
            field=models.PositiveIntegerField(default=0, verbose_name='ID способа доставки'),
        ),
    ]
