# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20171204_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='kladr_id',
            field=models.CharField(default=0, max_length=256, verbose_name='kladr_id'),
        ),
    ]
