# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20171204_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_point',
            field=models.CharField(default=0, max_length=256, null=True, verbose_name='ID пункта самовывоза'),
        ),
    ]
