# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_send_to_shiptor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=512, verbose_name='Промокод')),
                ('discount', models.PositiveIntegerField(verbose_name='Скидка по промокоду(в %)')),
            ],
            options={
                'verbose_name_plural': 'Промокоды',
                'verbose_name': 'Промокод',
            },
        ),
    ]
