# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_discount',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Размер скидки по промокоду'),
        ),
    ]
