# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_total_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_discount',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Размер скидки по промокоду'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='used',
            field=models.BooleanField(default=False, verbose_name='Использован'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('waiting', 'Ожидание'), ('confirmed', 'Подтвержден'), ('cancel', 'Отменен')], max_length=10, verbose_name='Статус заказа'),
        ),
    ]
