# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20171217_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_point_name',
            field=models.CharField(max_length=256, null=True, verbose_name='Пункт самовывоза'),
        ),
    ]
