# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-25 15:53
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_delivery_point_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesOrdersCoursescart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie', models.CharField(blank=True, max_length=48, null=True)),
                ('price', models.IntegerField()),
                ('total_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'courses_orders_coursescart',
            },
        ),
        migrations.CreateModel(
            name='CoursesOrdersOrdertickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField()),
                ('ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
            options={
                'managed': False,
                'db_table': 'courses_orders_ordertickets',
            },
        ),
        migrations.CreateModel(
            name='PracticumArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('contacts', models.TextField()),
                ('coordinates', models.CharField(max_length=42)),
            ],
            options={
                'managed': False,
                'db_table': 'practicum_area',
            },
        ),
        migrations.CreateModel(
            name='PracticumCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('organizer', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('sort_index', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'practicum_courses',
            },
        ),
        migrations.CreateModel(
            name='PracticumTickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'managed': False,
                'db_table': 'practicum_tickets',
            },
        ),
        migrations.CreateModel(
            name='PracticumTicketscategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'managed': False,
                'db_table': 'practicum_ticketscategory',
            },
        ),
        migrations.CreateModel(
            name='CoursesOrdersCoursesorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(max_length=10)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('total_count', models.IntegerField(blank=True, null=True)),
                ('extra_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'courses_orders_coursesorder',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='order_delivery',
            field=models.CharField(choices=[('without', 'без доставки'), ('shiptor', 'shiptor'), ('boxberry', 'boxberry'), ('b2c', 'b2c'), ('dpd', 'dpd'), ('iml', 'iml'), ('russian-post', 'Почта России'), ('pickpoint', 'pickpoint'), ('cdek', 'cdek'), ('shiptor-one-day', 'shiptor-one-day'), ('spsr', 'spsr'), ('shiptor-oversize', 'shiptor-oversize')], max_length=16, null=True, verbose_name='Способ доставки'),
        ),
    ]
