# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-13 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_directoradmitcurator_directoradmitdirectoradmit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorAdmitDirectorschild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'director_admit_directorschild',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DirectorAdmitProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'director_admit_program',
                'managed': False,
            },
        ),
    ]
