# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-04 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_directoradmitdirectorschild_directoradmitprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorAdmitBriefing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
            options={
                'managed': False,
                'db_table': 'director_admit_briefing',
            },
        ),
        migrations.CreateModel(
            name='DirectorAdmitCommunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
            options={
                'managed': False,
                'db_table': 'director_admit_community',
            },
        ),
        migrations.CreateModel(
            name='DirectorAdmitParentsadmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(max_length=10)),
                ('extra_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True)),
                ('passport_data', models.TextField(blank=True, null=True)),
                ('federal', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('post_index', models.CharField(blank=True, max_length=255, null=True)),
                ('inn', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('passport_scan', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_scan', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('text_1', models.TextField(blank=True, null=True)),
                ('text_2', models.TextField(blank=True, null=True)),
                ('text_3', models.TextField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'director_admit_parentsadmit',
            },
        ),
        migrations.CreateModel(
            name='DirectorAdmitYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
            options={
                'managed': False,
                'db_table': 'director_admit_year',
            },
        ),
    ]
